/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shailesh;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.kafka.clients.admin.NewTopic;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.kafka.annotation.EnableKafkaStreams;
import org.springframework.kafka.config.TopicBuilder;

@SpringBootApplication
@EnableKafkaStreams
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);
    }
    @Bean
    NewTopic salesEvents() {
        return TopicBuilder.name("sales-events-v1").partitions(3).replicas(1).build();
    }

    @Bean
    NewTopic notificationsEvents() {
        return TopicBuilder.name("notifications-events-v1").partitions(3).replicas(1).build();
    }

    @Bean
    ObjectMapper objectMapper() {
        return new ObjectMapper();
    }

}
